title: SC2RO
description: The Smart Citizen Cyber Resilience Ontology.

locale: "en-us"
remote_theme: "mmistakes/so-simple-theme@3.2.0"

skin: "/assets/css/skins/default.css"
search_full_content: true
